//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEAWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class COST
    {
        public int ID { get; set; }
        public int MemberTypeID { get; set; }
        public int CostTypeID { get; set; }
        public double CostPounds { get; set; }
    }
}
