//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEAWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHT
    {
        public int ClubMemberP1ID { get; set; }
        public Nullable<int> ClubMemberP2ID { get; set; }
        public System.TimeSpan TakeoffTime { get; set; }
        public System.TimeSpan LandingTime { get; set; }
        public int LaunchTypeID { get; set; }
        public int GliderID { get; set; }
        public int PayingMemberID { get; set; }
        public double Cost { get; set; }
    }
}
